baseurl = "http://thoughtvoyager.com"
languagecode = "en"
defaultcontentlanguage = "en"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  mainSections = ["posts"]

[params.homeInfoParams]
  Title = "ðŸŒ¿ Thought Voyager"
  Content = "Welcome to my digital garden. Here I explore ideas, reflect on life, and grow thoughts one note at a time."


[taxonomies]
tag = "tags"
category = "categories"


[permalinks]
  posts = "/posts/:slug/"
  home = "/"

[outputs]
  home = ["HTML", "JSON"]

